import { v } from "convex/values"

import { api, internal } from "./_generated/api"
import {
  internalAction,
  internalMutation,
  query,
} from "./_generated/server"
import { estimatedCallCents } from "./lib/budget"
import { cronsEnabled } from "./lib/cronGate"
import { extractMetricsFromArticles } from "./lib/llm"
import type { ExtractMetricsArticle } from "./lib/llm"

// First-class Miami metrics — auto-generated by the mega-desk when it
// finds a number worth promoting in the cited sources. Stored slug-
// keyed so re-runs that surface a fresher version of the same metric
// (e.g. updated census number) overwrite in place rather than
// accumulating duplicates.

const KIND = v.union(
  v.literal("number"),
  v.literal("number-with-delta"),
  v.literal("line"),
  v.literal("bars"),
  v.literal("rank"),
  v.literal("compare"),
)

const CITATION = v.object({
  url: v.string(),
  title: v.string(),
  publisher: v.string(),
  fetchedAt: v.number(),
})

// Public — most-recent metrics, optionally filtered by section
// relevance. Homepage carousel uses no filter; section pages can
// filter by their own slug to surface section-relevant metrics.
export const list = query({
  args: {
    sectionSlug: v.optional(v.string()),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, { sectionSlug, limit }) => {
    const cap = limit ?? 12
    const all = await ctx.db
      .query("metrics")
      .withIndex("by_generated")
      .order("desc")
      .take(cap * 4)
    const filtered = sectionSlug
      ? all.filter((m) => m.relatedSectionSlugs.includes(sectionSlug))
      : all
    return filtered.slice(0, cap)
  },
})

// Public — single metric by slug. Used by the article body's
// `[[metric:slug]]` inline-embed renderer once that's wired up.
export const getBySlug = query({
  args: { slug: v.string() },
  handler: async (ctx, { slug }) => {
    return await ctx.db
      .query("metrics")
      .withIndex("by_slug", (q) => q.eq("slug", slug))
      .unique()
  },
})

// Internal — invoked by the mega-desk when the LLM emits a metric
// alongside the run's drafts and events. Idempotent by slug: an
// existing row gets patched with the new payload + citations, a
// missing slug gets inserted.
export const upsertFromAgent = internalMutation({
  args: {
    slug: v.string(),
    title: v.string(),
    subtitle: v.optional(v.string()),
    kind: KIND,
    data: v.any(),
    unit: v.optional(v.string()),
    citations: v.array(CITATION),
    relatedTags: v.array(v.string()),
    relatedSectionSlugs: v.array(v.string()),
  },
  handler: async (ctx, args) => {
    const now = Date.now()
    const existing = await ctx.db
      .query("metrics")
      .withIndex("by_slug", (q) => q.eq("slug", args.slug))
      .unique()
    if (existing) {
      // Union the citations (dedup by URL) so the catalog accumulates
      // sources over time as different desks/runs surface the metric.
      const seen = new Set(existing.citations.map((c) => c.url))
      const merged = [...existing.citations]
      for (const c of args.citations) {
        if (seen.has(c.url)) continue
        seen.add(c.url)
        merged.push(c)
      }
      await ctx.db.patch(existing._id, {
        title: args.title,
        subtitle: args.subtitle,
        kind: args.kind,
        data: args.data,
        unit: args.unit,
        citations: merged,
        relatedTags: args.relatedTags,
        relatedSectionSlugs: args.relatedSectionSlugs,
        generatedAt: now,
      })
      return { mode: "updated" as const, id: existing._id }
    }
    const id = await ctx.db.insert("metrics", {
      slug: args.slug,
      title: args.title,
      subtitle: args.subtitle,
      kind: args.kind,
      data: args.data,
      unit: args.unit,
      citations: args.citations,
      relatedTags: args.relatedTags,
      relatedSectionSlugs: args.relatedSectionSlugs,
      generatedAt: now,
    })
    return { mode: "inserted" as const, id }
  },
})

// Retroactive metric extraction. Runs daily — pulls recently
// published articles, asks Opus to surface verifiably-stated numbers
// worth promoting to first-class metrics, and upserts each one with
// the source article's citations attached.
//
// This complements in-run extraction (which happens at draft time
// inside generateDrafts): catches numbers the mega-desk missed when
// it first processed the article. Sonnet is plenty for reading
// published bodies and pulling explicit numbers — no creative work.
const EXTRACT_MODEL = "claude-sonnet-4-6"
const EXTRACT_LOOKBACK_HOURS = 7 * 24
const EXTRACT_MAX_ARTICLES = 30

export const extractRecent = internalAction({
  args: {},
  handler: async (
    ctx,
  ): Promise<{
    scanned: number
    extracted: number
    upserted: number
    skipped: Array<string>
  }> => {
    if (!cronsEnabled()) {
      return { scanned: 0, extracted: 0, upserted: 0, skipped: ["crons-disabled"] }
    }
    const reservation = await ctx.runMutation(internal.budget.reserve, {
      estimatedCents: estimatedCallCents(EXTRACT_MODEL),
      label: "metricsExtractRecent",
    })
    if (!reservation.allowed) {
      return { scanned: 0, extracted: 0, upserted: 0, skipped: ["budget-cap"] }
    }
    const since = Date.now() - EXTRACT_LOOKBACK_HOURS * 3_600_000
    const recent = await ctx.runQuery(api.articles.publishedRecentForMerge, {
      sinceMs: since,
      limit: EXTRACT_MAX_ARTICLES,
    })
    if (recent.length === 0) {
      return { scanned: 0, extracted: 0, upserted: 0, skipped: ["no-articles"] }
    }
    const articles: Array<ExtractMetricsArticle> = recent.map((a) => ({
      slug: a.slug,
      title: a.title,
      dek: a.dek,
      body: a.body.slice(0, 2000),
      primaryPublisher: a.citations[0]?.publisher,
    }))
    const extracted = await extractMetricsFromArticles({
      model: EXTRACT_MODEL,
      articles,
    })
    const skipped: Array<string> = []
    let upserted = 0
    // Build a slug → article lookup so we can attach citations from
    // the article each metric was extracted from.
    const bySlug = new Map(recent.map((a) => [a.slug, a]))
    for (const m of extracted) {
      const article = bySlug.get(m.fromArticleSlug)
      if (!article) {
        skipped.push(`unmatched fromArticleSlug=${m.fromArticleSlug}`)
        continue
      }
      const citations = article.citations.map((c) => ({
        url: c.url,
        title: c.title,
        publisher: c.publisher ?? "Unknown",
        fetchedAt: c.fetchedAt,
      }))
      await ctx.runMutation(internal.metrics.upsertFromAgent, {
        slug: m.slug,
        title: m.title,
        subtitle: m.subtitle,
        kind: m.kind,
        data: m.data,
        unit: m.unit,
        citations,
        relatedTags: m.relatedTags,
        relatedSectionSlugs: m.relatedSectionSlugs,
      })
      upserted += 1
    }
    return {
      scanned: recent.length,
      extracted: extracted.length,
      upserted,
      skipped,
    }
  },
})
