import { authTables } from "@convex-dev/auth/server"
import { defineSchema, defineTable } from "convex/server"
import { v } from "convex/values"

export default defineSchema({
  ...authTables,

  sections: defineTable({
    slug: v.string(),
    name: v.string(),
    description: v.string(),
    accentColor: v.string(),
    order: v.number(),
    // Optional parent — when set, this is a sub-section. The parent's
    // section page surfaces articles from its own sectionId AND from every
    // child. Top-level sections leave this undefined.
    parentId: v.optional(v.id("sections")),
  })
    .index("by_slug", ["slug"])
    .index("by_order", ["order"])
    .index("by_parent", ["parentId"]),

  authors: defineTable({
    slug: v.string(),
    name: v.string(),
    bio: v.string(),
    avatar: v.optional(v.string()),
    title: v.optional(v.string()),
    kind: v.union(v.literal("agent"), v.literal("human")),
  }).index("by_slug", ["slug"]),

  articles: defineTable({
    slug: v.string(),
    title: v.string(),
    dek: v.string(),
    body: v.string(),
    heroImage: v.optional(v.string()),
    heroCaption: v.optional(v.string()),
    heroSource: v.optional(
      v.union(
        v.literal("source"),
        v.literal("unsplash"),
        v.literal("wikimedia"),
        v.literal("none"),
      ),
    ),
    sectionId: v.id("sections"),
    status: v.union(
      v.literal("draft"),
      v.literal("pending_review"),
      v.literal("published"),
      v.literal("archived"),
      v.literal("rejected"),
    ),
    publishedAt: v.optional(v.number()),
    createdAt: v.number(),
    tags: v.array(v.string()),
    // DEPRECATED: editorial pinning was removed in favor of computed
    // importance scoring (see lib/scoring.ts). Kept optional so existing
    // records validate; new inserts omit it. Drop the column + the
    // by_featured index in a follow-up push once values are unset.
    isFeatured: v.optional(v.boolean()),
    citations: v.array(
      v.object({
        url: v.string(),
        title: v.string(),
        publisher: v.optional(v.string()),
        fetchedAt: v.number(),
        snippet: v.optional(v.string()),
      }),
    ),
    agentSlug: v.optional(v.string()),
    agentRunId: v.optional(v.id("agentRuns")),
    derivedFromItems: v.array(v.id("ingestedItems")),
    // Miami neighborhoods this story is tied to. Populated by the desk's
    // LLM at draft time from a fixed allowed list (see lib/neighborhoods.ts).
    neighborhoods: v.optional(v.array(v.string())),
    // Related articles populated at draft time by the desk's LLM call.
    // Bidirectional: when X links to Y, both ends get the back-reference.
    relatedArticleIds: v.optional(v.array(v.id("articles"))),
    // Story arc clustering: any cluster of articles that transitively link
    // forms an arc. Set when a draft links to existing articles; merged if
    // it links across two existing arcs.
    storyArcId: v.optional(v.id("storyArcs")),
    // Denormalized full-text search blob = title + dek + tags. Maintained
    // at insert / update time. Optional so existing docs validate; queries
    // tolerate a missing value.
    searchableText: v.optional(v.string()),
    // Per-language translations of the user-facing copy. Generated by an
    // LLM action triggered on publish + on enrichment when the EN copy
    // changes. `sourceHash` is a sha of EN title+dek+body — when the EN
    // shifts, the hash mismatches and the row is flagged for re-translate
    // by the dashboard's "Translate backlog" button.
    translations: v.optional(
      v.object({
        es: v.optional(
          v.object({
            title: v.string(),
            dek: v.string(),
            body: v.string(),
            heroCaption: v.optional(v.string()),
            translatedAt: v.number(),
            sourceHash: v.string(),
          }),
        ),
      }),
    ),
  })
    .index("by_slug", ["slug"])
    .index("by_section_status_published", ["sectionId", "status", "publishedAt"])
    .index("by_status_created", ["status", "createdAt"])
    .index("by_status_published", ["status", "publishedAt"])
    .index("by_featured", ["isFeatured", "status", "publishedAt"])
    .index("by_story_arc", ["storyArcId"])
    // Full-text search across the title + a derived searchable blob. The
    // `searchableText` field is maintained at insert / update time as
    // `title + dek + tags.join(" ")` so a single index covers headline,
    // standfirst, and topic recall.
    .searchIndex("by_searchable", {
      searchField: "searchableText",
      filterFields: ["status", "sectionId"],
    }),

  article_authors: defineTable({
    articleId: v.id("articles"),
    authorId: v.id("authors"),
  })
    .index("by_article", ["articleId"])
    .index("by_author", ["authorId"]),

  sources: defineTable({
    name: v.string(),
    type: v.union(
      v.literal("rss"),
      v.literal("reddit"),
      v.literal("youtube"),
      v.literal("x"),
      v.literal("web"),
      v.literal("wikipedia-otd"),
    ),
    url: v.string(),
    sectionIds: v.array(v.id("sections")),
    enabled: v.boolean(),
    config: v.optional(v.any()),
    lastFetchedAt: v.optional(v.number()),
    lastFetchStatus: v.optional(v.string()),
    lastFetchError: v.optional(v.string()),
    lastFetchItemCount: v.optional(v.number()),
    lastFetchNewCount: v.optional(v.number()),
  })
    .index("by_type", ["type"])
    .index("by_enabled", ["enabled"]),

  ingestedItems: defineTable({
    sourceId: v.id("sources"),
    externalId: v.string(),
    url: v.string(),
    title: v.string(),
    snippet: v.optional(v.string()),
    body: v.optional(v.string()),
    mediaUrl: v.optional(v.string()),
    publishedAt: v.optional(v.number()),
    fetchedAt: v.number(),
    consumed: v.boolean(),
  })
    .index("by_source_external", ["sourceId", "externalId"])
    .index("by_source_fetched", ["sourceId", "fetchedAt"])
    .index("by_consumed_fetched", ["consumed", "fetchedAt"]),

  agents: defineTable({
    slug: v.string(),
    name: v.string(),
    sectionId: v.id("sections"),
    authorId: v.id("authors"),
    model: v.string(),
    systemPrompt: v.string(),
    beats: v.array(v.string()),
    enabled: v.boolean(),
    lastRunAt: v.optional(v.number()),
    maxItemsPerRun: v.number(),
    maxDraftsPerRun: v.number(),
    lookbackHours: v.number(),
  })
    .index("by_slug", ["slug"])
    .index("by_section", ["sectionId"]),

  agentRuns: defineTable({
    agentId: v.id("agents"),
    startedAt: v.number(),
    finishedAt: v.optional(v.number()),
    status: v.union(
      v.literal("running"),
      v.literal("succeeded"),
      v.literal("failed"),
    ),
    log: v.array(v.string()),
    itemsConsidered: v.number(),
    draftsCreated: v.number(),
    errorMessage: v.optional(v.string()),
  })
    .index("by_agent_started", ["agentId", "startedAt"])
    .index("by_started", ["startedAt"]),

  editors: defineTable({
    email: v.string(),
    role: v.union(v.literal("admin"), v.literal("editor")),
  }).index("by_email", ["email"]),

  // Per-article timeline. Every meaningful change (draft created, desk
  // augmented with new sources, editor edited, status moved) writes one row.
  // Powers the History panel in the admin queue editor.
  articleRevisions: defineTable({
    articleId: v.id("articles"),
    at: v.number(),
    kind: v.union(
      v.literal("draft_created"),
      v.literal("agent_augmented"),
      v.literal("agent_enriched"),
      v.literal("editor_edited"),
      v.literal("status_changed"),
    ),
    // Provenance — exactly one of these is set per row.
    agentSlug: v.optional(v.string()),
    agentRunId: v.optional(v.id("agentRuns")),
    editorEmail: v.optional(v.string()),
    // Lightweight summary of what changed. Body diffs aren't stored; we
    // record which fields touched + counts for citations / source items.
    changedFields: v.optional(v.array(v.string())),
    citationsAdded: v.optional(v.number()),
    sourceItemsAdded: v.optional(v.number()),
    statusBefore: v.optional(v.string()),
    statusAfter: v.optional(v.string()),
    note: v.optional(v.string()),
  }).index("by_article_at", ["articleId", "at"]),

  // A story arc groups articles that transitively reference each other.
  // Title is seeded from the first article and may be re-titled later.
  // lastActivityAt drives "still developing" treatment in the UI.
  storyArcs: defineTable({
    title: v.string(),
    startedAt: v.number(),
    lastActivityAt: v.number(),
  }).index("by_lastActivity", ["lastActivityAt"]),

  // Events power the public /events calendar. Distinct from articles —
  // articles describe what happened, events are what's happening. Indexed
  // by start time so calendar / "upcoming" queries are O(log n).
  events: defineTable({
    title: v.string(),
    description: v.string(),
    startsAt: v.number(),
    endsAt: v.optional(v.number()),
    allDay: v.boolean(),
    // Sub-category. `general` = things-to-do bucket; `meeting` = community
    // meetings / public hearings; `notice` = public notices; `holiday` =
    // civic / cultural holidays; `deal` = offers and deals. Optional so
    // pre-existing events without a kind default to `general` in queries.
    kind: v.optional(
      v.union(
        v.literal("general"),
        v.literal("meeting"),
        v.literal("notice"),
        v.literal("holiday"),
        v.literal("deal"),
      ),
    ),
    locationName: v.optional(v.string()),
    locationAddress: v.optional(v.string()),
    neighborhood: v.optional(v.string()),
    url: v.optional(v.string()),
    imageUrl: v.optional(v.string()),
    price: v.optional(v.string()),
    sectionId: v.optional(v.id("sections")),
    articleId: v.optional(v.id("articles")),
    status: v.union(
      v.literal("pending_review"),
      v.literal("approved"),
      v.literal("rejected"),
    ),
    // Provenance — set when a desk's LLM extracted the event from sources.
    agentSlug: v.optional(v.string()),
    agentRunId: v.optional(v.id("agentRuns")),
    derivedFromItems: v.optional(v.array(v.id("ingestedItems"))),
    createdAt: v.number(),
  })
    .index("by_starts", ["startsAt"])
    .index("by_status_starts", ["status", "startsAt"])
    .index("by_section_starts", ["sectionId", "status", "startsAt"])
    .index("by_kind_starts", ["kind", "status", "startsAt"]),
})
