/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as SiteTagSlugRouteImport } from './routes/_site/tag.$slug'
import { Route as SiteSectionSlugRouteImport } from './routes/_site/section.$slug'
import { Route as SiteNeighborhoodSlugRouteImport } from './routes/_site/neighborhood.$slug'
import { Route as SiteEventSlugRouteImport } from './routes/_site/event.$slug'
import { Route as AdminAdminTaxonomyRouteImport } from './routes/_admin/admin.taxonomy'
import { Route as AdminAdminSourcesRouteImport } from './routes/_admin/admin.sources'
import { Route as AdminAdminSettingsRouteImport } from './routes/_admin/admin.settings'
import { Route as AdminAdminRunsRouteImport } from './routes/_admin/admin.runs'
import { Route as AdminAdminPublishedRouteImport } from './routes/_admin/admin.published'
import { Route as AdminAdminEventsIdRouteImport } from './routes/_admin/admin.events.$id'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteTagSlugRoute = SiteTagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSectionSlugRoute = SiteSectionSlugRouteImport.update({
  id: '/section/$slug',
  path: '/section/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNeighborhoodSlugRoute = SiteNeighborhoodSlugRouteImport.update({
  id: '/neighborhood/$slug',
  path: '/neighborhood/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEventSlugRoute = SiteEventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const AdminAdminTaxonomyRoute = AdminAdminTaxonomyRouteImport.update({
  id: '/admin/taxonomy',
  path: '/admin/taxonomy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSourcesRoute = AdminAdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRunsRoute = AdminAdminRunsRouteImport.update({
  id: '/admin/runs',
  path: '/admin/runs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPublishedRoute = AdminAdminPublishedRouteImport.update({
  id: '/admin/published',
  path: '/admin/published',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminEventsIdRoute = AdminAdminEventsIdRouteImport.update({
  id: '/admin/events/$id',
  path: '/admin/events/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/published': typeof AdminAdminPublishedRoute
  '/admin/runs': typeof AdminAdminRunsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/sources': typeof AdminAdminSourcesRoute
  '/admin/taxonomy': typeof AdminAdminTaxonomyRoute
  '/event/$slug': typeof SiteEventSlugRoute
  '/neighborhood/$slug': typeof SiteNeighborhoodSlugRoute
  '/section/$slug': typeof SiteSectionSlugRoute
  '/tag/$slug': typeof SiteTagSlugRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/events/$id': typeof AdminAdminEventsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/published': typeof AdminAdminPublishedRoute
  '/admin/runs': typeof AdminAdminRunsRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/sources': typeof AdminAdminSourcesRoute
  '/admin/taxonomy': typeof AdminAdminTaxonomyRoute
  '/event/$slug': typeof SiteEventSlugRoute
  '/neighborhood/$slug': typeof SiteNeighborhoodSlugRoute
  '/section/$slug': typeof SiteSectionSlugRoute
  '/tag/$slug': typeof SiteTagSlugRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/events/$id': typeof AdminAdminEventsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_site/': typeof SiteIndexRoute
  '/_admin/admin/published': typeof AdminAdminPublishedRoute
  '/_admin/admin/runs': typeof AdminAdminRunsRoute
  '/_admin/admin/settings': typeof AdminAdminSettingsRoute
  '/_admin/admin/sources': typeof AdminAdminSourcesRoute
  '/_admin/admin/taxonomy': typeof AdminAdminTaxonomyRoute
  '/_site/event/$slug': typeof SiteEventSlugRoute
  '/_site/neighborhood/$slug': typeof SiteNeighborhoodSlugRoute
  '/_site/section/$slug': typeof SiteSectionSlugRoute
  '/_site/tag/$slug': typeof SiteTagSlugRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/events/$id': typeof AdminAdminEventsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/login'
    | '/admin/published'
    | '/admin/runs'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/taxonomy'
    | '/event/$slug'
    | '/neighborhood/$slug'
    | '/section/$slug'
    | '/tag/$slug'
    | '/admin/'
    | '/admin/events/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/admin/published'
    | '/admin/runs'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/taxonomy'
    | '/event/$slug'
    | '/neighborhood/$slug'
    | '/section/$slug'
    | '/tag/$slug'
    | '/admin'
    | '/admin/events/$id'
  id:
    | '__root__'
    | '/_admin'
    | '/_site'
    | '/admin/login'
    | '/_site/'
    | '/_admin/admin/published'
    | '/_admin/admin/runs'
    | '/_admin/admin/settings'
    | '/_admin/admin/sources'
    | '/_admin/admin/taxonomy'
    | '/_site/event/$slug'
    | '/_site/neighborhood/$slug'
    | '/_site/section/$slug'
    | '/_site/tag/$slug'
    | '/_admin/admin/'
    | '/_admin/admin/events/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/tag/$slug': {
      id: '/_site/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof SiteTagSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/section/$slug': {
      id: '/_site/section/$slug'
      path: '/section/$slug'
      fullPath: '/section/$slug'
      preLoaderRoute: typeof SiteSectionSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/neighborhood/$slug': {
      id: '/_site/neighborhood/$slug'
      path: '/neighborhood/$slug'
      fullPath: '/neighborhood/$slug'
      preLoaderRoute: typeof SiteNeighborhoodSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/event/$slug': {
      id: '/_site/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof SiteEventSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_admin/admin/taxonomy': {
      id: '/_admin/admin/taxonomy'
      path: '/admin/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AdminAdminTaxonomyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/sources': {
      id: '/_admin/admin/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminAdminSourcesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/settings': {
      id: '/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/runs': {
      id: '/_admin/admin/runs'
      path: '/admin/runs'
      fullPath: '/admin/runs'
      preLoaderRoute: typeof AdminAdminRunsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/published': {
      id: '/_admin/admin/published'
      path: '/admin/published'
      fullPath: '/admin/published'
      preLoaderRoute: typeof AdminAdminPublishedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/events/$id': {
      id: '/_admin/admin/events/$id'
      path: '/admin/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminAdminEventsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminPublishedRoute: typeof AdminAdminPublishedRoute
  AdminAdminRunsRoute: typeof AdminAdminRunsRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminSourcesRoute: typeof AdminAdminSourcesRoute
  AdminAdminTaxonomyRoute: typeof AdminAdminTaxonomyRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminEventsIdRoute: typeof AdminAdminEventsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminPublishedRoute: AdminAdminPublishedRoute,
  AdminAdminRunsRoute: AdminAdminRunsRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminSourcesRoute: AdminAdminSourcesRoute,
  AdminAdminTaxonomyRoute: AdminAdminTaxonomyRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminEventsIdRoute: AdminAdminEventsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SiteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
  SiteEventSlugRoute: typeof SiteEventSlugRoute
  SiteNeighborhoodSlugRoute: typeof SiteNeighborhoodSlugRoute
  SiteSectionSlugRoute: typeof SiteSectionSlugRoute
  SiteTagSlugRoute: typeof SiteTagSlugRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
  SiteEventSlugRoute: SiteEventSlugRoute,
  SiteNeighborhoodSlugRoute: SiteNeighborhoodSlugRoute,
  SiteSectionSlugRoute: SiteSectionSlugRoute,
  SiteTagSlugRoute: SiteTagSlugRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
